name: Deploy with docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: datasaude
    steps:
      - name: building app
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 177.93.0.0
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          command_timeout: 5m
          script: |
            echo "Criando diretório"
            mkdir -p ~/app
            cd ~/app/
            echo "Clone repositório"
            [ -d datasaude-worker ] && rm -rf datasaude-worker
            git clone https://${{ secrets.GIT_USER }}:${{ secrets.GIT_TOKEN }}@github.com/cbeloni/datasaude-worker.git
            echo "Criando .env"
            cat <<EOF > datasaude-worker/.env
              MYSQL_HOST='${{ secrets.MYSQL_HOST }}'
              MYSQL_ROOT_PASSWORD='${{ secrets.MYSQL_ROOT_PASSWORD }}'
              MYSQL_DATABASE='${{ secrets.MYSQL_DATABASE }}'
              MYSQL_USER='${{ secrets.MYSQL_USER }}'
              MYSQL_PASSWORD='${{ secrets.MYSQL_PASSWORD }}'
              MYSQL_VOLUME='${{ secrets.MYSQL_VOLUME }}'
              AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}'
              AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}'
              ENDPOINT_URL=${{ secrets.ENDPOINT_URL }}
              OPEN_CAGE_API_KEY='${{ secrets.OPEN_CAGE_API_KEY }}'
              GOOGLE_MAPS_API_KEY='${{ secrets.GOOGLE_MAPS_API_KEY }}'
              PATH_VOLUME='${{ secrets.PATH_VOLUME }}'
              DATASAUDE_ML_URL='${{ secrets.DATASAUDE_ML_URL }}'
              RABBIT='${{ secrets.RABBIT }}'
              DATASAUDE_API='${{ secrets.DATASAUDE_API }}'            
            EOF
            echo "Buildando projeto"
            cd datasaude-worker
            docker-compose down api
            docker-compose up -d --no-deps --build api